services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - MLFLOW_TRACKING_URI=mlruns
      - CORS_ORIGINS=http://localhost:8501
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    environment:
      - API_PORT=8000
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    depends_on:
      - api
